<?php
/**
 * EmployeesApiControllerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ApiTeste_LU
 *
 * An API to allow users to obtain information of employees and post new information aswell
 *
 * OpenAPI spec version: 1.0.0
 * Contact: matheus.silva@criticalsoftware.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.8
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * EmployeesApiControllerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class EmployeesApiControllerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for employeesGet
     *
     * employeesGet.
     *
     */
    public function testEmployeesGet()
    {
    }

    /**
     * Test case for employeesIdDelete
     *
     * employeesIdDelete.
     *
     */
    public function testEmployeesIdDelete()
    {
    }

    /**
     * Test case for employeesIdGet
     *
     * employeesIdGet.
     *
     */
    public function testEmployeesIdGet()
    {
    }

    /**
     * Test case for employeesPost
     *
     * employeesPost.
     *
     */
    public function testEmployeesPost()
    {
    }
}
